// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function safeGetEnv(key: string): string | undefined {
  try {
    const metaEnv =
      typeof import.meta !== "undefined"
        ? (import.meta as { env?: Record<string, string | undefined> }).env
        : undefined;
    if (metaEnv?.[key]) {
      return metaEnv[key];
    }
  } catch {
    // ignore
  }

  try {
    if (typeof process !== "undefined" && process.env?.[key]) {
      return process.env[key];
    }
  } catch {
    // ignore
  }

  return undefined;
}

export function getSupabaseConfig() {
  const url =
    safeGetEnv("VITE_SUPABASE_URL") ||
    safeGetEnv("SUPABASE_URL") ||
    "https://vnzllryrnuowvppgzzmc.supabase.co";

  const key =
    safeGetEnv("VITE_SUPABASE_PUBLISHABLE_KEY") ||
    safeGetEnv("SUPABASE_PUBLISHABLE_KEY") ||
    (typeof window !== "undefined"
      ? localStorage.getItem("sb_publishable_key") ||
        localStorage.getItem("VITE_SUPABASE_PUBLISHABLE_KEY") ||
        ""
      : "");

  return { url, key };
}

export function isSupabaseConfigured(): boolean {
  const { url, key } = getSupabaseConfig();
  return Boolean(url && key);
}

export function setSupabasePublishableKey(key: string) {
  if (typeof window !== "undefined") {
    localStorage.setItem("sb_publishable_key", key.trim());
    _supabase = undefined;
  }
}

function createSupabaseClient() {
  const { url, key } = getSupabaseConfig();
  const effectiveKey = key || "placeholder-anon-key";

  return createClient<Database>(url, effectiveKey, {
    global: {
      fetch: createSupabaseFetch(effectiveKey),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
